pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        // Add any Maven build steps here
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
        // Add any Node.js build steps here
      }
    }
    stage('Deploy to Kubernetes') {
      environment {
        KUBECONFIG = '/home/ashokvm/.minikube/config'
      }
      steps {
        script {
          // Example: Use kubectl to apply Kubernetes manifests
          sh 'kubectl apply -f /Jenkins-Zero-To-Hero/multi-stage-multi-agent/deployment.yml'
          // You may need to replace '/path/to/your/kubernetes/manifests' with the actual path to your Kubernetes manifest files
        }
      }
    }
  }
}
